name: bhukkd
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  http: any
  geolocator: '^4.0.3'
  flare_flutter: ^1.5.4
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.6
  html: any
  sqflite: any
  path_provider: any
  async_loader: ^0.1.2
  date_format: "^1.0.4"
  url_launcher: any
  intl: ">=0.14.0"
  font_awesome_flutter: ^8.4.0
  cached_network_image: ^2.0.0
  async: any
  photo_view: ^0.4.2
  avataaar_image: ^1.0.8
  flutter_datetime_picker: ^1.4.0
  time_slot_picker: ^0.0.1
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  grouped_buttons: ^1.0.4
  flutter_masked_text: ^0.8.0
  rflutter_alert: ^1.0.3
  toast: ^0.1.5
  flutter_mailer: ^0.4.1+2
  flutter_swiper: ^1.1.4
  flutter_custom_clippers: ^0.1.1
  permission_handler: ^5.0.0+hotfix.6
  extended_image: ^0.7.3-dev



# Firebase dependencies
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: any



  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  progress_indicators: ^0.1.2


flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf


  uses-material-design: true


  assets:
    - assets/animations/near_by_rest_loading.flr
    - assets/animations/restaurant_details.flr
    - assets/animations/searching.flr
    - assets/animations/comment_loading_content_loading.flr
    - assets/animations/warning.flr
    - assets/animations/search_location.flr
    - assets/animations/Loading animation.flr
    - assets/animations/loading_Untitled.flr
    - assets/animations/dotLoader.flr
    - assets/animations/loading_2.flr
    - assets/animations/no_connection.flr
    - assets/animations/top_restaurant_loading.flr
    - assets/api/config.json
    - assets/images/default.jpg
    - assets/images/no_data.gif
    - assets/images/default-avatar.jpg
    - assets/images/icons/user.png
    - assets/images/icons/bookings.png
    - assets/images/icons/help.png
    - assets/images/icons/payment_option.png
    - assets/images/icons/privacy.png
    - assets/images/icons/delivery.png
    - assets/images/icons/dine_out.png
    - assets/images/icons/night_life.png
    - assets/images/icons/catching_up.png
    - assets/images/icons/takeaway.png
    - assets/images/icons/cafe.png
    - assets/images/icons/daily_menu.png
    - assets/images/icons/breakfast.png
    - assets/images/icons/lunch.png
    - assets/images/icons/dinner.png
    - assets/images/icons/pubs_bars.png
    - assets/images/icons/friendly_delivery.png
    - assets/images/icons/default_userImage.png
    - assets/images/icons/chair_red.png
    - assets/images/icons/chair_green.png
    - assets/images/icons/chair_gray.png
    - assets/images/icons/club_lounges.png
    - assets/images/not_found.gif
    - assets/images/
