name: bhukkd
description: A spicy hot place to find food that lets you book a table in nearby restaurants.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  splashscreen: ^1.2.0
  flutter:
    sdk: flutter
  http: any
  geolocator: '^4.0.3'
  flare_flutter: ^1.5.4
  scoped_model: ^1.0.1
  shared_preferences: any
  html: any
  sqflite: any
  path_provider: any
  async_loader: ^0.1.2
  date_format: "^1.0.4"
  url_launcher: "^3.0.1"
  intl: ">=0.14.0"
  font_awesome_flutter: ^8.4.0
  cached_network_image: any
  async: any
  photo_view: ^0.4.2
  avataaar_image: ^1.0.2
  flutter_datetime_picker: ^1.2.5
  time_slot_picker: ^0.0.1
  flutter_map: ^0.6.1
  latlong: ^0.6.1
  grouped_buttons: ^1.0.4
  flutter_masked_text: ^0.8.0
  rflutter_alert: ^1.0.3



  # Firebase dependencies
  firebase_auth: ^0.8.4
  cloud_firestore: ^0.10.1
  google_sign_in: ^4.0.0


  # Api- key 1:0bc8d74fdefd3601d84a0d52ffa01901
  # Api- key 2:021a533947da652345753f4825586fd4
  # Api- key 3:8266ad12c4e2c8e8b48c63f9bb7a6d1b
  # Map- Api key:sk.eyJ1IjoibmF2ZWVuMTE2OTUiLCJhIjoiY2p5c21iMDB3MDF4MDNsbXk5emV3eGlwYyJ9.ceo9CMq7F791AdpT4mME2Q

  # Email: naveen.satyam.developers@gmail.com
  # Password: bhukkd_satyam_naveen

  # SHA1: 87:ED:D5:9E:68:84:07:AB:AA:B7:A0:CC:EB:70:E9:84:4E:B6:AA:91

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: any
  progress_indicators: ^0.1.2
#
#flutter_icons:
#  image_path: "assets/images/icon.png"
#  android: true
#  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf   
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf   
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/animations/near_by_rest_loading.flr
  - assets/animations/restaurant_details.flr
  - assets/animations/Search Loading.flr
  - assets/animations/Loading animation.flr
  - assets/animations/loading_Untitled.flr
  - assets/animations/dotLoader.flr
  - assets/animations/loading_2.flr
  - assets/animations/top_restaurant_loading.flr
  - assets/api/config.json
  - assets/images/default.jpg
  - assets/images/default-avatar.jpg
  - assets/images/icons/user.png
  - assets/images/icons/bookings.png
  - assets/images/icons/help.png
  - assets/images/icons/payment_option.png
  - assets/images/icons/privacy.png
  - assets/images/icons/delivery.png
  - assets/images/icons/dine_out.png
  - assets/images/icons/night_life.png
  - assets/images/icons/catching_up.png
  - assets/images/icons/takeaway.png
  - assets/images/icons/cafe.png
  - assets/images/icons/daily_menu.png
  - assets/images/icons/breakfast.png
  - assets/images/icons/lunch.png
  - assets/images/icons/dinner.png
  - assets/images/icons/pubs_bars.png
  - assets/images/icons/friendly_delivery.png
  - assets/images/icons/club_lounges.png
  - assets/images/not_found.gif
  - assets/images/


  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
